#!/usr/bin/env bash

PORT=8081

# ./mvnw spring-boot:run \
#   -Dspring-boot.run.arguments="--server.port=$PORT"

# Forward all arguments to mvnw
./mvnw "$@" spring-boot:run \
  -Dspring-boot.run.arguments="--server.port=$PORT"