spring.application.name=example
spring.banner.charset=UTF-8

# Use PORT from .env or environment, fallback to 8081
server.port=${PORT:8081}

# Custom properties
my.custom.property="Hello - This is a basic SpringBoot khmer course by #Hkimhab in dev"
my.custom.property.int = 1393
