# Support extension: Spring Boot Tools - id: "vmware.vscode-spring-boot"

spring.config.import=optional:file:.env[.properties]

spring.application.name=example
spring.banner.charset=UTF-8

# Change port 8080 to 8081
server.port=8081

# Custom properties
my.custom.property="Hello - This is a basic SpringBoot khmer course by #Hkimhab"
my.custom.property.int = 1393

# Customize active profile to dev
# dev == application-dev.properties
# test,dev,staging = Get the last exist valid application-{profile}.properties file, in this case application-staging.properties, but since it does not exist, it will get application-dev.properties
# spring.profiles.active=test,dev,staging

# Disable devtools restart and livereload
spring.devtools.restart.enabled=${RESTART_ENABLED:true}
spring.devtools.livereload.enabled=${LIVERELOAD_ENABLED:true}

# Enable default user
swagger.auth.required=${SWAGGER_AUTH_REQUIRED:false}
spring.security.user.name=${APP_SECURITY_USER_NAME:admin}
spring.security.user.password=${APP_SECURITY_USER_PASSWORD:admin12sldfkjsdlfjsdklfsBitcoin3}
spring.security.user.roles=${APP_SECURITY_USER_ROLES:USER}

# Hibernate will detect the new @JoinColumn and add the column for you. No manual SQL needed.
# spring.jpa.hibernate.ddl-auto=update