# Support extension: Spring Boot Tools - id: "vmware.vscode-spring-boot"

spring.application.name=example
spring.banner.charset=UTF-8

# Change port 8080 to 8081
server.port=8081

# Custom properties
my.custom.property="Hello - This is a basic SpringBoot khmer course by #Hkimhab"
my.custom.property.int = 1393

# Customize active profile to dev
# dev == application-dev.properties
# test,dev,staging = Get the last exist valid application-{profile}.properties file, in this case application-staging.properties, but since it does not exist, it will get application-dev.properties
# spring.profiles.active=test,dev,staging

# Disable devtools restart and livereload
# spring.devtools.restart.enabled=false
# spring.devtools.livereload.enabled=false