spring.application.name=example
spring.banner.charset=UTF-8

# Change port 8080 to 8081
server.port=8081

# Custom properties
my.custom.property="Hello - This is a basic SpringBoot khmer course by #Hkimhab"
